#!/bin/bash
echo "=== Cash4Crash Cron Job Setup ==="
echo ""
echo "To automate the ETL process on your Linux VPS, you need to set up a cron job."
echo "Since the backend is running inside a Docker container, we will use 'docker exec' to run the script."
echo ""
echo "1. Open your crontab by running:"
echo "   crontab -e"
echo ""
echo "2. Add the following line to the bottom of the file to run the ETL script every day at midnight:"
echo "   0 0 * * * docker exec cash4crash-backend-1 python etl.py >> /var/log/cash4crash_etl.log 2>&1"
echo ""
echo "(Note: Depending on the folder name where you run docker-compose, the container name might be different."
echo " Use 'docker ps' to verify the exact backend container name if 'cash4crash-backend-1' doesn't work)."
echo ""
echo "That's it! Your analytics database will now update automatically every night."
